name: Applications

on:
  push:
    branches: [main]

jobs:
  deploy-demo:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: yarn nx run @dot-connect/demo:build

      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: dot-connect-demo
          directory: apps/demo/dist
